import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export const metadata = {
  title: 'Ogami portfolio - Admin Panel',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang='en'>
      <body>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          {/* <UserButton /> */}
        </SignedIn>
        {children}
      </body>
    </html>
  </ClerkProvider>
  )
}
